server:
  port: 8090

spring:
  application:
    name: security-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  thymeleaf:
    prefix: classpath:/templates/ # 不加这个，接口自动到resources/templates目录下找与接口返回的相同名称的html
    cache: false
    suffix: .html

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/






